---
- name: check for short-circuit
  raw: "> /dev/null command -v youtube-dl;"
  register: installed
  ignore_errors: True
  changed_when: False

- name: set should_run fact
  set_fact:
    should_run: "{{installed is failed or not youtube_dl_should_shortcircuit}}"

- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: install youtube-dl with default package manager
  action: "{{backcompat_pkg_mgr}} name={{package_name}}"
  become: true
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install youtube-dl with dnf
  command: dnf install -y {{package_name}}
  args:
    creates: /usr/bin/youtube-dl
  become: true
  when: backcompat_pkg_mgr == "dnf"
